baseURL = 'https://levenrok.github.io/laravel-notes/'
languageCode = 'en-us'
title = 'Laravel Notes'
theme = 'hugo-book'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'auto'

  BookSection = '*'